# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0007_auto_20160623_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kd.Order'),
            preserve_default=False,
        ),
    ]
