# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0009_remove_order_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 4, 23, 59, 4, 272759, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='kd.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.CharField(max_length=10, verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
