# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0010_auto_20160704_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 5, 2, 57, 9, 640556, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='receiver_instance', to='kd.EndUser', verbose_name='\u6536\u4ef6\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 5, 2, 57, 18, 910343, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='sender_instance', to='kd.EndUser', verbose_name='\u53d1\u4ef6\u4eba'),
            preserve_default=False,
        ),
    ]
