# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0011_auto_20160705_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c'),
        ),
    ]
