# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0012_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='\u91cd\u91cf')),
                ('sender_address', models.CharField(max_length=50, null=True, verbose_name='\u53d1\u8d27\u5730\u5740')),
                ('receiver_address', models.CharField(max_length=50, null=True, verbose_name='\u6536\u8d27\u5730\u5740')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0b\u5355\u65f6\u95f4')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='\u9ad8\u5ea6')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='\u5bbd\u5ea6')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='\u957f\u5ea6')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAssignShippingUser',
            fields=[
                ('shipping_user_id', models.CharField(max_length=50, null=True, verbose_name='\u5bc4\u9001\u4eba\u90ae\u7bb1')),
                ('primKey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kd.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteBid',
            fields=[
                ('shipping_user_id', models.CharField(max_length=50, null=True, verbose_name='\u5bc4\u9001\u4eba\u90ae\u7bb1')),
                ('bid_price', models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c')),
                ('primKey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kd.Quote')),
            ],
        ),
        migrations.AlterField(
            model_name='enduser',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u516c\u53f8\u540d'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sender_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_info', to='kd.EndUser', verbose_name='\u5ba2\u6237'),
        ),
    ]
