# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0014_quote_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='note',
            new_name='notes',
        ),
    ]
