# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0015_auto_20160731_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('external_order_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='\u5916\u90e8\u5355\u53f7')),
                ('external_checking_method', models.CharField(max_length=1000, verbose_name='\u67e5\u8be2\u65b9\u5f0f')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kd.Order')),
            ],
        ),
    ]
